default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: root_and_fruits_development

test:
  <<: *default
  database: root_and_fruits_test

production:
  <<: *default
  database: root_and_fruits
